before_script:
  - export CI_DISABLE_CURNN_TEST=true

variables:
  CI_IMAGE_TAG: 'cuda'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

.gpu:
  extends:
    - .julia:1.5
    - .test
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - mkdir $JULIA_DEPOT_PATH # Pkg3.jl#325
    - julia --project -e 'using Pkg;
                          Pkg.add("CUDA");
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test(; coverage=true);'

test:1.5:
  extends: .gpu

test:dev:
  extends: .gpu
  allow_failure: true
