name = "OMEinsum"
uuid = "ebe7aa44-baf0-506c-a96f-8464559b3922"
authors = ["Andreas Peter <andreas.peter.ch@gmail.com>"]
version = "0.1.0"

[deps]
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
